server-flask/__init__.py
from flask import Flask
from .views import main, post, reply
from flask_migrate import Migrate
from flask_pymongo import PyMongo

import config

app = Flask(__name__)
db = PyMongo()
migrate = Migrate()

app.config.from_object(config)

db.init_app(app)
migrate.init_app(app, db)

app.register_blueprint(main.bp)
app.register_blueprint(post.bp)
app.register_blueprint(reply.bp)

server-flask/views/main.py
from flask import Blueprint, url_for
from ..service.post_service import PostService
from werkzeug.utils import redirect

bp = Blueprint('main', __name__, url_prefix='/')
postService = PostService()

@bp.route('/')
def index():
    return redirect(url_for('post._list'))

server-flask/views/post.py
from flask import Blueprint, render_template, url_for, request
from ..service.post_service import PostService
from ..service.reply_service import ReplyService
from werkzeug.utils import redirect
from  ..form.post import PostForm

bp = Blueprint('post', __name__, url_prefix='/post')
post_service = PostService()
reply_service = ReplyService()

@bp.route('/', methods=('GET',))
def _list():
    post_list = post_service.get_post_list()
    return render_template('post_list.html', post_list=post_list)

@bp.route('/create/', methods=('GET','POST',))
def create():
    form = PostForm()
    if request.method == 'GET':
        return render_template('post_create.html', form=form)

    elif request.method == 'POST':
        post_service.create(subject=form.subject.data, content=form.content.data)
        return redirect(url_for('post._list'))
    else:
        return redirect(url_for('post._list'))


@bp.route('/<int:post_id>/')
def detail(post_id):
    post_detail = post_service.get_post(id=post_id)
    reply_list = reply_service.get_reply_list(post_id=post_id)
    return render_template('post_detail.html', post_detail=post_detail, reply_list=reply_list)

server-flask/views/reply.py
from flask import Blueprint, request, url_for
from ..service.reply_service import ReplyService
from werkzeug.utils import redirect

bp = Blueprint('reply', __name__, url_prefix='/reply')
reply_service = ReplyService()

@bp.route('/<int:post_id>/', methods=('POST',))
def create(post_id):
    content = request.form['content']
    reply_service.create(post_id=post_id, content=content)
    return redirect(url_for('post.detail', post_id=post_id))

server-flask/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Table</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>
<body>

    <div class="container">
        <br>
        <h1 class="text-center">
            <a href="#">JNine's Free Board!</a>
        </h1>
        <br>


        <table class="table table-hover table-striped text-center" style="border: 1px solid;">
            <thead>
                <th>번호</th>
                <th>제목</th>
                <th>글쓴이</th>
                <th>조회수</th>
            </thead>
                <tr>
                    <td>1</td>
                    <td>Title_1</td>
                    <td>Cha4ser</td>
                    <td>1</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Title_2</td>
                    <td>Cha4ser</td>
                    <td>10</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Title_3</td>
                    <td>Cha4ser</td>
                    <td>12</td>
                </tr>
            <tbody>

            </tbody>

        </table>

        <hr>
        <div>
            <ul class="pagination justify-content-center">
                <li><a href="#" style="margin-right:5px ;" class="text-secondary"></a>1</li>
                <li><a href="#" style="margin-right:5px ;" class="text-secondary"></a>2</li>
                <li><a href="#" style="margin-right:5px ;" class="text-secondary"></a>3</li>
                <li><a href="#" style="margin-right:5px ;" class="text-secondary"></a>4</li>
                <li><a href="#" style="margin-right:5px ;" class="text-secondary"></a>5</li>
                <li><a href="#" style="margin-right:5px ;" class="text-secondary"></a>6</li>
            </ul>

        </div>

        <a class="btn btn-outline-info btn-right">글쓰기</a>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>

server-flask/templates/post_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create post</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
<div class="container">
    <h5 class="my-3 border-bottom pb-2">New Post</h5>
    <form method="post" class="post-form my-3">

        <div class="form-group">
            <label for="subject">{{ form.subject.label }}</label>
            <input type="text" class="form-control" name="subject" id="subject">
        </div>

        <div class="form-group">
            <label for="content">{{ form.content.label }}</label>
            <textarea type="text" class="form-control" name="content" id="content" rows="5"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
</body>
</html>

server-flask/templates/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ post_detail.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ post_detail.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ post_detail.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{ reply_list.count() }}개의 답변이 있습니다.</h5>
    {% for reply in reply_list %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ reply.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ reply.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{{ url_for('reply.create', post_id=post_detail.id) }}" method="post" class="my-3">
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
</div>

server-flask/templates/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if post_list %}
        {% for post in post_list %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>
                <a href="{{url_for('post.detail', post_id=post.id)}}">{{ post.subject }}</a>
            </td>
            <td>{{ post.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    <a href="{{ url_for('post.create') }}" class="btn btn-primary">New Post</a>
</div>

</body>
</html>